lib/wishlister_web/router.ex
defmodule WishlisterWeb.Router do
  use WishlisterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug WishlisterWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WishlisterWeb do
    pipe_through :browser # Use the default browser stack

    get "/", VenueController, :index
    get "/wishlist", VenueController, :list
    post "/venues", VenueController, :create
    delete "/venues/:id", VenueController, :delete

  end

  scope "/auth", WishlisterWeb do
    pipe_through :browser

    get "/signout", UserController, :signout
    get "/:provider", UserController, :request
    get "/:provider/callback", UserController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", WishlisterWeb do
  #   pipe_through :api
  # end
end

lib/wishlister_web/views/layout_view.ex
defmodule WishlisterWeb.LayoutView do
  use WishlisterWeb, :view
end

lib/wishlister_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wishlist</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">  
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo title">
          Wishlist
        </a>
        <ul class="right hide-on-med-and-down">
          <%= if @conn.assigns[:user] do %>
            <li>
              <span class="username"><%= @conn.assigns[:user].name %></span>
            </li>
            <li class="avatar">
              <img src="<%= @conn.assigns[:user].avatar %>" alt="Avatar" class="circle">
            <li>
              <%= link to: user_path(@conn, :signout) do %>
                <i class="material-icons" title="Logout">exit_to_app</i>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>