lib/wishlister_web/router.ex
defmodule WishlisterWeb.Router do
  use WishlisterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug WishlisterWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WishlisterWeb do
    pipe_through :browser # Use the default browser stack

    get "/", VenueController, :index
    get "/wishlist", VenueController, :list
    post "/venues", VenueController, :create
    delete "/venues/:id", VenueController, :delete

  end

  scope "/auth", WishlisterWeb do
    pipe_through :browser

    get "/signout", UserController, :signout
    get "/:provider", UserController, :request
    get "/:provider/callback", UserController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", WishlisterWeb do
  #   pipe_through :api
  # end
end

lib/wishlister_web/controllers/list_controller.ex
require IEx;
defmodule WishlisterWeb.ListController do
  use WishlisterWeb, :controller


  alias Wishlister.Checkins

  plug WishlisterWeb.Plugs.RequireAuth when action in [
    :list,
    :create,
    :delete
  ]

  def index(conn, _params) do
    render conn, "index.html"
  end

  def list(conn, _params) do
    user = conn.assigns[:user]

    wishlist = Checkins.get_user_wishlist(user.id)

    friends_checkins =
      Checkins.recents_friends_checkins(user.token)
      |> Checkins.filter_not_added_venues(wishlist)

    render conn, "list.html", checkins: friends_checkins, wishlist: wishlist
  end

  def create(conn, %{"checkin" => venue}) do
    user = conn.assigns.user
    case Checkins.add_venue_to_wishlist(user, venue) do
      {:ok, _venue} ->
        conn
        |> put_flash(:info, "Venue added on your wishlist")
        |> redirect(to: list_path(conn, :list))
      {:error, _changeset} ->
        conn
        |> put_flash(:error, "Failed to add venue on your wishlist")
        |> redirect(to: list_path(conn, :list))
    end
  end

  def delete(conn, %{"id" => venue_id}) do
    Checkins.remove_venue_from_wishlist(venue_id)

    conn
    |> put_flash(:info, "Venue removed from your wishlist!")
    |> redirect(to: list_path(conn, :list))
  end
end

lib/wishlister_web/templates/list/index.html.eex
<div class="container-index">
  <%= if !@conn.assigns[:user] do %>
    <%= button to: auth_path(@conn, :request, "foursquare"), method: "get", class: "btn-large waves-effect waves-light" do %>
      <i class="material-icons right">send</i>Sign in with Foursquare
    <% end %>
  <% end %>
</div>

lib/wishlister_web/templates/list/list.html.eex
<div class="wishlist">
  <h4>User wishlist</h4>

  <div class="recent-container">
    <%= for wish <- @wishlist do %>
      <div class="row">
        <div class="col s12 m6">
          <div class="card small">
            <%= button to: list_path(@conn, :delete, wish), method: "delete", title: "Remove", class: "btn-floating halfway-fab waves-effect waves-light blue" do %>
              <i class="material-icons">delete</i>
            <% end %> 
            <div class="card-image">
              <img src="<%= wish.image_url %>">
            </div>
            <div class="card-content">
              <p><%= wish.name %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="recents-checkins">
  <h4>Recents Friends Checkins</h4>

  <div class="recent-container">
    <%= for checkin <- @checkins do %>
      <div class="row">
        <div class="col s12 m6">
          <div class="card small">
            <%= button to: list_path(@conn, :create, checkin: checkin), method: "post", title: "Add", class: "btn-floating halfway-fab waves-effect waves-light red" do %>
              <i class="material-icons">add</i>
            <% end %>
            <div class="card-image">
              <img src="<%= checkin.image_url %>">
            </div>
            <div class="card-content">
              <p><%= checkin.name %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>